apiVersion: v1
kind: Pod
metadata:
  name: dns-monitor
spec:
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
    fsGroup: 9915       # Ensures proper permissions for mounted volumes
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - dss
            - d3i00.sciclone.wm.edu
  containers:
  - name: dns-monitor
    image: ghcr.io/wmgeolab/nicfi-download:latest
    command: ["python", "/sciclone/home/dsmillerrunfol/K8S_DNS_RES_ERROR/dns-monitor.py"]
    resources:
      requests:
        cpu: "12"        # Minimum of 12 cores
      limits:
        cpu: "12"        # Maximum of 12 cores
    volumeMounts:
    - name: sciclone-volume
      mountPath: /sciclone/
    securityContext:
      allowPrivilegeEscalation: false
  volumes:
  - name: sciclone-volume
    nfs:
      server: 128.239.59.144
      path: /sciclone/
  restartPolicy: Always
