apiVersion: v1
kind: Pod
metadata:
  name: dns-monitor
spec:
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
  containers:
  - name: dns-monitor
    image: python:3.8-slim
    command: ["python", "/sciclone/geograd/K8S_DNS_RES_ERROR/dns-monitor.py"]
    volumeMounts:
    - name: sciclone-volume
      mountPath: /sciclone/geograd/K8S_DNS_RES_ERROR/
  volumes:
  - name: sciclone-volume
    nfs:
      server: 128.239.59.144
      path: /sciclone/geograd/K8S_DNS_RES_ERROR/
  restartPolicy: Always
