apiVersion: v1
kind: Pod
metadata:
  name: dns-test-postgres
  labels:
    app: dns-test-postgres
spec:
  securityContext:
    runAsUser: 71032  # Required for NFS compatibility
    runAsGroup: 9915  # Required for NFS group access
  containers:
  - name: postgres
    image: postgis/postgis:14-3.3  # PostGIS-enabled PostgreSQL image
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "dns-test-postgres"  # User to be created on first run
    - name: POSTGRES_PASSWORD
      value: ""  # Empty password (trust authentication enabled)
    - name: POSTGRES_DB
      value: "dns-test-postgres"  # Database to be created on first run
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "trust"  # Allow connections without a password
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data  # Persistent data directory
    resources:
      requests:
        memory: "8Gi"
        cpu: "2"
      limits:
        memory: "16Gi"
        cpu: "4"
  volumes:
  - name: postgres-data
    nfs:
      server: 128.239.59.144  # Replace with your NFS server IP
      path: /sciclone/geograd/tmp
  # NFS path for PostgreSQL data storage
---
apiVersion: v1
kind: Service
metadata:
  name: dns-test-postgres
spec:
  selector:
    app: dns-test-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
