apiVersion: v1
kind: Pod
metadata:
  name: internal-dns-test-web
  labels:
    app: internal-dns-test-web
spec:
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
  containers:
  - name: dns-test-server
    image: python:3.8-slim
    command: ["python", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: internal-dns-test-web
spec:
  selector:
    app: internal-dns-test-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
